### ISSUE TITLE
Experiencing HTTPS Connection Timeouts

### ISSUE THREAD

**Issue by jaygun** [sdague/mychevy#12]
* mychevy version: 2.0.1
* Python version: 3.8.2
* Operating System: Windows and Linux

### Description

Using this module as a part of Home Assistant. A little while after we fixed the authentication issue, I started to receive timeouts. After some debugging outside of Home Assistant, I have found updating the Chrome version of the user agent seems to play nice with the Chevrolet API. The earliest version of Chrome I have found to return a proper response is Chrome/75.0.3770.80

### Traceback

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mychevy/__init__.py", line 146, in run
    self.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/mychevy/__init__.py", line 128, in update
    self.cars = self._client.update_cars()
  File "/usr/local/lib/python3.8/site-packages/mychevy/mychevy.py", line 309, in update_cars
    self._fetch_car(c)
  File "/usr/local/lib/python3.8/site-packages/mychevy/mychevy.py", line 106, in f_retry
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mychevy/mychevy.py", line 293, in _fetch_car
    res = self.session.get(session, headers=headers,
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='my.chevrolet.com', port=443): Read timed out. (read timeout=120)
```

**Comment by jaygun** [comment]
@sdague - Can you look at this? Thanks!

**Comment by dennyreiter** [comment]
second this.  The user agent update works.
